language: shell
os: linux
arch: amd64
dist: bionic

services: docker

branches:
  only:
    - master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=$(date +%Y%m%d)
  - docker build --pull -t alvisisme/linux-c:$TAG .
  - docker push alvisisme/linux-c:$TAG
  - docker tag alvisisme/linux-c:$TAG alvisisme/linux-c:latest
  - docker push alvisisme/linux-c:latest
